### ISSUE TITLE
Error: Can't resolve 'process/browser' in exifr 

### ISSUE THREAD

**Issue by K3TH3R** [laravel-mix/laravel-mix#2737]
-   Laravel Mix Version: 6.0.4 (`npm list --depth=0`)
-   Node Version (`node -v`): 14.15.3
-   NPM Version (`npm -v`):  1.22.10 (yarn)
-   OS: Mac

### Description: 
I re-installed my node_modules today and the installed version of Mix was resolved to `6.0.6`. With this dependency change, Laravel Mix starts failing with the following error:
```
ERROR in ./node_modules/exifr/dist/full.esm.mjs 1:293-300
Module not found: Error: Can't resolve 'process/browser' in '/Users/Kether/Trendspek/trendspek/node_modules/exifr/dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 1 error
error Command failed with exit code 1.
```
I am able to run my repo successfully from 6.0.0 -> 6.0.3, but it starts throwing this error as soon as I move to 6.0.4 (although the process never exits).

**Comment by celiamaure** [comment]
Hello,
I have the same issue with Axios package. Laravel Mix fails with this error:
`ERROR in ../../shop/libraries/js/website/node_modules/axios/lib/defaults.js 21:20-27
Module not found: Error: Can't resolve 'process/browser' in '/var/www/web/shop/libraries/js/website/node_modules/axios/lib'

webpack compiled with 1 error`

It works on 6.0.3 and starts throwing this error on 6.0.4

**Comment by thecrypticace** [comment]
Hmm this shouldn't be a problem. The polyfills were added to fix support for the process global.

Can you see if `process` exists as a package inside your node_modules folder?

**Comment by celiamaure** [comment]
Ok my fault.. Axios was on 0.19, I switched to 0.21 and it fixed the error. Thank you

**Comment by K3TH3R** [comment]
@thecrypticace It's showing `process` version `0.11.10` in the `node_modules` directory:
![Screen Shot 2021-01-06 at 1 23 36 pm](https://user-images.githubusercontent.com/11901111/103721704-73645f00-5022-11eb-8ddb-4624c153e62d.png)

**Comment by v1r0x** [comment]
I have the same problem as @celiamaure 
There is no `process` folder in `node_modules`

**Comment by 100phel** [comment]
I'm having the same issue with laravel-mix 6.0.10 and exifr package:

`ERROR in ./node_modules/exifr/dist/full.esm.mjs 1:293-300
Module not found: Error: Can't resolve 'process/browser' in '/home/sergei/Developer/coalliance/projects/monolith/node_modules/exifr/dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.`

**Comment by medhi** [comment]
Same issue here with mysticatea/event-target-shim:

https://github.com/mysticatea/event-target-shim/issues/37

https://github.com/mysticatea/event-target-shim/blob/71b37d173c9672883b2fc810a37b5a7c9a33119f/scripts/test.ts#L201

**Comment by htulibacki** [comment]
Same here with lezer package on Mix 6.0.11.

```
ERROR in ./node_modules/lezer/dist/index.es.js 586:23-30
Module not found: Error: Can't resolve 'process/browser' in '/Users/hutu/www/grafmag/node_modules/lezer/dist'
Did you mean 'browser.js'?
BREAKING CHANGE: The request 'process/browser' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

webpack compiled with 1 error
```

**Comment by htulibacki** [comment]
Ok, the solution in my case was to set `legacyNodePolyfills` option to `false`.

More info on this feature: https://laravel-mix.com/docs/6.0/legacy-node-polyfills

**Comment by tcetin** [comment]
@htulibacki I am facing same problem. It didnt solve the problem.

**Comment by volnistii11** [comment]
> Хорошо, решение в моем случае состояло в том, чтобы установить `legacyNodePolyfills`option на `false`.
> 
> Более подробная информация об этой функции: https://laravel-mix.com/docs/6.0/legacy-node-polyfills

and in which file should it be written?

**Comment by yefta-me** [comment]
Suddenly got this issue. Anyone has idea about this matter except by adding `legacyNodePolyfills` option to `false`. I already did that, and not working.

**Comment by FabianKaufmann** [comment]
@volnistii11 to the `webpack.mix.js` file in the root above the `mix.js()` call.

**Comment by jringeisen** [comment]
Make sure the `mix.options({legacyNodePolyfills: false})` is ran before the mix.js(). I noticed that running it after caused FullCalendar to throw a bunch of errors.

**Comment by jringeisen** [comment]
Anyone else having issues with this on the M1 Macbook Pro? I have identical environments setup on my iMac (Intel) and my Macbook (M1) but when I do this on my M1 Macbook it breaks my code. But works fine on my iMac (Intel).

**Comment by Gompje** [comment]
@jringeisen nope. Its probably because your M1 has a newer version of things? I didn't have this issue on my M1 until I upgraded a bunch of dep and did a full reset of the .lock file. 

Think it must be the version of Webpack -- given I had to change the ignore config for moment. bit annoying given it was already on v5.x I mean things  like this shouldn't break inside the same major version..don't they 😏   🤷‍♀️ 

I did have to set the option to false like @htulibacki  said above before I could build. 

Or it could just be node. the version on M1 is different than x86 and I had a LOT of issues with the latest. v14.18 is proven to be the best for now on M1. way to many issues with the latest.

**Comment by jringeisen** [comment]
@Gompje I currently have the environments on both machines set exactly the same with the same versions of everything and the code is pulled from GitHub so the code is the same on both machines. I'll keep playing around and see if I can narrow down the issue but as of right now it's annoying not being able to work from my laptop.

**Comment by Gompje** [comment]
@jringeisen I was too fast to cry victory as well :( 

while I can build, I cannot run my code given it does not include the `process/browser` I need for mermaid. I only have one machine, my M1 air. It was working fine before I upgrade some dep.

lets see  if I can find the cullprit

**Comment by Gompje** [comment]
@jringeisen well.. I have it working now (I think) except for 1 js module. (mermaidjs) I've been running in circles.  it gives the same 'could not resolve' error and me a headache. Maybe tomorrow will bring new insights. sigh

I did have to set the flag to `true` though. and now things "work" except mermaid. although I still have to test more.

What is weird is that even when I did include all old things webpack said it removed, it still wouldn't process mermaid while before this worked without issues.

I had laravel-mix `v6.0.19` before all this. and I thought I had webpack 5 but now I am in doubt and confused. found out that yarn info isn't really given the correct info when using a .lock file. and I have lots of packages.

very weird.  and indeed VERY annoying. I only have the one machine, removed the other one a few months ago because the M1 was working perfectly (somewhat) 

🤔 right now I don't even know if it is an M1 issue! damn.

**Comment by thecrypticace** [comment]
I _might_ have a fix for this. Can you try the master branch and see if it happens to be fixed for you?

**Comment by Gompje** [comment]
@jringeisen sorry I feel like a stalker now, but: I got it working! 🎉  Seemed like some older legacy import code -- that loaded the mermaidjs seemed to have caused my issue. I think because one of the changes webpack made is the way/order it loads things. I updated that and it works for now.

So For now I can confirm it works fully on my M1. If you want help comparing notes/versions → shoot! :)

**Comment by Gompje** [comment]
@thecrypticace trippy: same time commenting :)  anyway I am not sure if I am a good test-person given that it was some legacy code thing that seemed to have caused the issue. (and setting the flag to `true`) but if you want, I can/will test. Tomorrow at the earliest (EU timezone)

**Comment by jringeisen** [comment]
@thecrypticace I pulled in the master branch recompiled successfully but my site was still broken. I removed the `  legacyNodePolyfills: false,` recompiled successfully and it seems fixed. Before, if I compiled without the `legacyNodePolyfills: false,` it wouldn't compile and would throw an error. Whatever you changed seems to work.

**Comment by thecrypticace** [comment]
I've published 6.0.38. It contains a handful of changes — the fix for this is one of them. I'm gonna close this issue but please feel free to do additional testing and comment if it isn't.
